# Generated by Django 3.1.5 on 2021-02-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='many_answers',
            field=models.BooleanField(default=False, verbose_name='Для решения можно выбрать несколько ответов'),
        ),
    ]
